CENTER_COORDS = (63.41771242884644, 10.40335350836009)  # x and y coordinates are specified in meters from this point
JUNCTION_MARGIN = 10  # junctions are generated by shrinking roads JUNCTION_MARGIN meters away from the connection point of the junction, then connecting every lane of the roads going into the junction
BIKING_WIDTH = 1.5  # default width for bike lanes
DRIVING_WIDTH = 3.5  # default width for car lanes
SAVE_RELATIVE_COORDINATES = False  # save relative coordinates to resulting file where (0, 0) is the center of the data. This is necessary for software like esmini which create artefacts due to floating point errors


#detail_levels = set(chain.get("detaljnivå") for seq in nvdb for chain in seq["veglenker"])
detail_levels = [
    #"Kjørebane",
    "Vegtrase",
    "Vegtrase og kjørebane"
]
road_types = [
    "Enkel bilveg",
    #"Fortau",
    #"Gang- og sykkelveg",
    #"Gangfelt",
    #"Gangveg",
    "Kanalisert veg",
    "Rundkjøring",
    #"Sykkelveg",
    #"Trapp"
]
